theme: jekyll-theme-cayman
title: Welcome Frodo of the Shire

description: This is, as you know, a testing site.

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"
  Resources:
    - Google search: "http://google.com/"
    - VertNet: "http://vertnet.org/"
    - GBIF: "https://gbif.org/"
  Author's home: "http://vertnet.org"
